services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Adeliom\EasyBlockBundle\Block\BlockInterface:
            tags: [ 'easy_block.block' ]

    Adeliom\EasyBlockBundle\Block\BlockCollection:
        autoconfigure: true
        public: true
        arguments:
            - !tagged easy_block.block

    easy_block.block_collection:
        alias: Adeliom\EasyBlockBundle\Block\BlockCollection

    Adeliom\EasyBlockBundle\Twig\EasyBlockExtension:
        public: true
        tags:
            - { name: twig.extension }

    easy_block.twig_extension:
        alias: Adeliom\EasyBlockBundle\Twig\EasyBlockExtension

    Adeliom\EasyBlockBundle\Editor\SharedBlockType:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator.default"
            - "%easy_block.class%"
        tags: [ 'easy_editor.block' ]

    easy_block.maker.make_shared_block:
        class: Adeliom\EasyBlockBundle\Maker\MakeSharedBlock
        public: false
        arguments:
            - '@maker.file_manager'
        tags:
            - { name: maker.command }

    Adeliom\EasyBlockBundle\Block\Helper:
        public: true
        arguments:
            - '@twig'
            - '@event_dispatcher'
            - '@easy_block.block_collection'
            - '@doctrine.orm.entity_manager'
            - '%easy_block.class%'
        tags:
            - { name: twig.runtime }

    easy_block.block_helper:
        alias: Adeliom\EasyBlockBundle\Block\Helper

    Adeliom\EasyBlockBundle\DataCollector\BlockCollector:
        arguments:
            - "@easy_block.block_helper"
        tags:
            - name: data_collector
              template: '@EasyBlock/profiler/collector.html.twig'
              id: Adeliom\EasyBlockBundle\DataCollector\BlockCollector
